In [5]:
d1 = {10, 20, 30, 40, 50, 60, 70, 80}   #3rd
d1

{10, 20, 30, 40, 50, 60, 70, 80}

In [3]:
range(5)

range(0, 5)

In [7]:
list(range(5))

[0, 1, 2, 3, 4]

In [13]:
for i in range(5):    # one argument (stop value)
    print(i)


0
1
2
3
4


In [9]:
for i in range(0, 5):  # two argument(start, stop) value
    print(i)


0
1
2
3
4


In [15]:
for i in range(1, 10,2):  # three argument (start, stop, step)
    print(i)

1
3
5
7
9


In [17]:
for i in range(2, 20, 3):
    print(i)


2
5
8
11
14
17


In [19]:
for i in range(10, 0, -2):  # Reverse order
    print(i)


10
8
6
4
2


In [21]:
for i in range(40, 0, -4):
    print(i)


40
36
32
28
24
20
16
12
8
4


In [23]:
r = range(10)
r

range(0, 10)

In [25]:
for i in range(0, 10):
    print(i)


0
1
2
3
4
5
6
7
8
9


In [27]:
range(10, 40)

range(10, 40)

In [29]:
range(10, 20, 5)

range(10, 20, 5)

In [31]:
for i in range(10, 20, 5):
    print(i)

10
15


In [33]:
for i in range(10, 40, 5):
    print(i)

10
15
20
25
30
35


In [35]:
range(10, 40, 4, 1 )  # you can pass only three argument

TypeError: range expected at most 3 arguments, got 4

In [37]:
r1 = range(10, 40, 5)
list(range(r1))

TypeError: 'range' object cannot be interpreted as an integer

In [39]:
r1 = range(10, 40, 5)
r1

range(10, 40, 5)

In [41]:
r1

range(10, 40, 5)

In [43]:
for i in r1:
    print(i)

10
15
20
25
30
35


In [45]:
numbers = [10, 20, 30, 40, 50, 60, 70, 80]  # take element (2 index to 6 index) (n-1), 7-1 = 6
print(numbers[2:7])

[30, 40, 50, 60, 70]


In [47]:
text = "PythonProgramming"
print(text[2:7])


thonP


In [ ]:
[::-1]  sequence[start:end:step]   step = -1  means (reverse order)

In [49]:
text = "Python"
reversed_text = text[::-1]
print(reversed_text)

nohtyP


In [51]:
numbers = [1, 2, 3, 4, 5]
reversed_numbers = numbers[::-1]
print(reversed_numbers)

[5, 4, 3, 2, 1]


### NumPy Crash Course

In [54]:
import numpy as np

In [56]:
np.__version__

'1.26.4'

In [58]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

### Creating Arrays

In [61]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [63]:
type(my_list)

list

In [65]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [67]:
type(arr)

numpy.ndarray

In [69]:
numpy.ndarray

NameError: name 'numpy' is not defined

In [ ]:
np.

In [71]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
np.arange(3.0)

array([0., 1., 2.])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr = np.arange(2, 20, 3)  # 2 se 19 till, every step difference of 3 
print(arr)

[ 2  5  8 11 14 17]


In [79]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [81]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [83]:
np.arange(20, 10)

array([], dtype=int32)

In [85]:
arr = np.arange(1.5, 5.5, 0.5)  # 1.5 se 5.5 till, 0.5 step
print(arr)

[1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [87]:
np.arange(20, 10, -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [89]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [91]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [93]:
np.arange(-20, -10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [95]:
np.arange(30, 20) # 1st argument always be < 2nd argument

array([], dtype=int32)

In [101]:
ar = np.arange(-30, 20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [103]:
np.arange(10,10)

array([], dtype=int32)

In [107]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [109]:
np.arange()

TypeError: arange() requires stop to be specified.

In [111]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [113]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [115]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [117]:
np.zeros(3)  # parameter tunning

array([0., 0., 0.])

In [119]:
np.zeros(5, dtype=int)  #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [121]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [123]:
arr = np.zeros((3,3))  # Default dtype=float
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [125]:
arr = np.zeros((2,3), dtype=bool)
print(arr)

[[False False False]
 [False False False]]


In [129]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [131]:
np.zeros((10, 30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [133]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [135]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [137]:
n = (6, 7)
n1 = (6, 8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [139]:
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [141]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [143]:
np.ones(3)

array([1., 1., 1.])

In [145]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [147]:
np.ones(4)

array([1., 1., 1., 1.])

In [149]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [151]:
np.ones((5,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [153]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [157]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [159]:
np.ones(2)

array([1., 1.])

In [161]:
rand(3,2)

NameError: name 'rand' is not defined

In [163]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [165]:
np.random.rand(5)

array([0.21979316, 0.32179956, 0.26012286, 0.96934344, 0.8262132 ])

In [167]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [169]:
np.random.rand(2,4) #np.random.rand(2, 4) means generating a 2x4 array where the values are randomly chosen between 0 and 1.

array([[0.13337273, 0.40623271, 0.75640538, 0.19256752],
       [0.41890848, 0.53372994, 0.52095276, 0.46133625]])

In [171]:
np.random.rand(3,2)

array([[0.32066339, 0.51073871],
       [0.20204884, 0.5741536 ],
       [0.87171708, 0.90462863]])

In [179]:
np.random.randint(2,4)   #np.random.randint(low, high, size)

2

In [ ]:
np.random.randint(2, 4) means generating a random integer
between 2 and 4, but 4 is not included 
(i.e., the possible values are 2 or 3).

In [181]:
np.random.rand(6)   #numpy is package, random is module, rand is function, 

array([0.40497468, 0.95613084, 0.40685818, 0.30063189, 0.84345981,
       0.76625374])

In [194]:
arr = np.random.randint(2, 4, size=(2, 3))
print(arr)

[[3 2 2]
 [2 3 3]]


In [208]:
np.random.randint(2,20)  # create any number (2 to 20)

16

In [214]:
np.random.randint(0,1) 

0

In [219]:
np.random.randint(10,20,5) ##np.random.randint(low, high, size)

array([11, 10, 18, 11, 12])

In [ ]:
np.random.randint(10, 20, 5) means generating 5 random integers between 10 and 20, but 20 is not included
(i.e., the possible values will be between 10 and 19).

In [223]:
np.random.randint(1,6,4)

array([1, 4, 1, 5])

In [225]:
np.random.randint(-30,20,10)

array([ -2,   4, -18, -22,  -4, -10, -25,  -7,   7,   9])