### 4th

In [1]:
import numpy as np

In [17]:
np.random.randint(20,30,10)

array([21, 23, 20, 29, 21, 26, 21, 25, 27, 23])

In [ ]:
In Python, np.random.randint(20, 30, 10) means that it generates 10 random integers between
20 and 29 (30 is excluded) using NumPy's randint function.
np.random.randint(start, stop, size)
start = 20 → Lower bound (inclusive)
stop = 30 → Upper bound (exclusive)
size = 10 → Generates 10 numbers

In [19]:
np.random.randint(5,9)

7

In [ ]:
In Python, np.random.randint(5, 9) means that it will generate a single random integer between 5 and 8 (9 is excluded).

In [21]:
np.random.randint(10,21,3)

array([19, 12, 14])

In [23]:
np.random.randint(1,12,10)

array([ 6,  2, 10,  4, 10,  1,  4,  2,  4,  6])

In [25]:
np.random.randint(10,40,(10,10))

array([[39, 26, 34, 28, 28, 15, 23, 28, 27, 11],
       [38, 14, 10, 35, 25, 25, 39, 18, 22, 20],
       [16, 14, 29, 18, 17, 26, 21, 11, 31, 26],
       [18, 30, 35, 31, 21, 31, 22, 22, 34, 21],
       [23, 26, 17, 17, 36, 12, 21, 33, 25, 20],
       [15, 25, 38, 28, 25, 27, 11, 18, 37, 19],
       [30, 24, 31, 31, 34, 15, 12, 10, 32, 34],
       [13, 39, 35, 20, 39, 18, 16, 38, 12, 31],
       [13, 19, 19, 29, 14, 14, 39, 36, 20, 15],
       [17, 12, 26, 25, 26, 26, 12, 38, 29, 33]])

In [ ]:
np.random.randint(start, stop, size)
start = 10 → Lower bound (inclusive)
stop = 40 → Upper bound (exclusive)
size = (10, 10) → Generates a 10x10 matrix (2D array) of random integers

In [27]:
np.random.randint(1,100,(12,12))

array([[82, 70, 22, 35, 52, 11, 31, 89, 39, 86, 33, 60],
       [32, 43, 59, 38, 59, 36, 32,  6,  4, 53, 12, 14],
       [ 9, 97,  6, 17, 18, 19, 78, 13, 37, 17, 84, 35],
       [31, 35, 37, 59, 43, 75, 56, 75, 43, 54, 64, 23],
       [52, 47, 34, 70, 13, 98, 93,  8, 83, 21, 84, 31],
       [12, 87, 65, 69, 76, 53, 44, 23, 36, 40, 70, 99],
       [52, 90, 21, 74, 52, 41, 47, 44, 38, 67, 94, 54],
       [ 2, 87, 15, 58, 21,  6, 64, 88, 98, 89, 21, 29],
       [43, 56, 23, 14, 59, 81, 27, 50, 35, 38, 90, 48],
       [11, 61, 71, 86, 44, 57, 95, 10, 46, 93,  7, 62],
       [73, 76, 55, 68, 37, 28,  8, 80, 78, 14, 14, 56],
       [14, 31, 38, 54, 71, 14, 35, 63, 28,  1, 80, 12]])

In [29]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
np.arange(1, 13) → Generates numbers from 1 to 12 (13 is excluded).
.reshape(12,1) → Reshapes the array into 12 rows and 1 column (a column vector).

In [31]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.random.randint(10,20,(5,4))

array([[16, 14, 18, 17],
       [10, 14, 14, 18],
       [11, 11, 17, 13],
       [17, 12, 11, 15],
       [19, 18, 12, 12]])

In [35]:
b = np.random.randint(10,20,(5,5))
b

array([[19, 15, 15, 13, 14],
       [19, 12, 18, 12, 19],
       [16, 17, 19, 16, 18],
       [19, 10, 16, 10, 12],
       [18, 19, 18, 14, 17]])

In [37]:
type(b)

numpy.ndarray

In [39]:
np.random.randint(1,13,(5,4))

array([[ 8,  1, 11,  6],
       [ 1,  4,  1,  6],
       [12,  3,  7, 12],
       [ 4,  4,  2,  2],
       [ 4, 11,  1,  7]])

In [41]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [ ]:
The command np.arange(1,13).reshape(5,4) will result in an error because
np.arange(1,13) generates only 12 elements, but  trying to reshape it into a
5×4 (20 elements) matrix, which is not possible.

In [43]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [45]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [47]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Slicing in matrix

In [50]:
np.random.randint(10,20,(5,4))

array([[18, 18, 14, 15],
       [14, 16, 17, 18],
       [19, 13, 16, 10],
       [12, 19, 10, 16],
       [11, 16, 13, 18]])

In [52]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 16, 17, 11],
       [15, 18, 14, 13],
       [12, 18, 13, 15],
       [12, 12, 13, 12],
       [12, 14, 18, 12]])

In [54]:
type(b)

numpy.ndarray

In [56]:
b[:]

array([[17, 16, 17, 11],
       [15, 18, 14, 13],
       [12, 18, 13, 15],
       [12, 12, 13, 12],
       [12, 14, 18, 12]])

In [60]:
b[1:3]

array([[15, 18, 14, 13],
       [12, 18, 13, 15]])

In [62]:
b

array([[17, 16, 17, 11],
       [15, 18, 14, 13],
       [12, 18, 13, 15],
       [12, 12, 13, 12],
       [12, 14, 18, 12]])

In [66]:
b[2:4]

array([[12, 18, 13, 15],
       [12, 12, 13, 12]])

In [68]:
b = np.array([
    [1,  2,  3],   # Row 0
    [4,  5,  6],   # Row 1
    [7,  8,  9],   # Row 2
    [10, 11, 12],  # Row 3
    [13, 14, 15]   # Row 4
])

print(b[2:4])  # Slicing rows 2 and 3  means 2 row and 3rd row

[[ 7  8  9]
 [10 11 12]]


In [70]:
b[1,2]

6

In [72]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [74]:
b[1,2]    # like first row second coloum

6

In [76]:
b[2,2]

9

In [80]:
b[1,2]

6

In [84]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [92]:
c[2:4]

array([[21, 32, 38, 16, 34, 36],
       [27, 26, 23, 39, 16, 20]])

In [19]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [21]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 10, 11, 18],
       [11, 16, 17, 11],
       [10, 19, 17, 10],
       [14, 10, 16, 15],
       [14, 11, 13, 18]])

In [23]:
b[1,3]

11

In [25]:
b[1,-1]

11

In [27]:
c = np.random.randint(10,40,(6,6))
c

array([[21, 12, 21, 13, 35, 31],
       [10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29],
       [17, 19, 29, 37, 32, 38],
       [21, 19, 27, 35, 32, 10],
       [13, 33, 39, 37, 35, 37]])

In [29]:
c[2:3]

array([[23, 15, 18, 27, 36, 29]])

In [31]:
c

array([[21, 12, 21, 13, 35, 31],
       [10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29],
       [17, 19, 29, 37, 32, 38],
       [21, 19, 27, 35, 32, 10],
       [13, 33, 39, 37, 35, 37]])

In [33]:
c[1,-1]

18

In [ ]:
          0cl  1cl  2cl   3cl  4cl  5cl

 0 rw    ([[21,  12,  21,  13,  35,  31],..  -6 row
 1 rw      [10,  37,  37,  26,  24,  18],.... -5 rw
 2 rw     [23,   15,  18,   27,  36,  29],....  -4 rw
 3 rw     [17,   19,   29,   37,  32, 38],..... -3 rw
 4 rw    [21,    19,   27,   35,   32, 10],....   -2 rw  
 5 rw    [13,    33,   39,   37,   35,  37]])..... -1 rw

         -5cl   -4cl   -3cl   -2cl  -1cl  -0cl

In [35]:
c

array([[21, 12, 21, 13, 35, 31],
       [10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29],
       [17, 19, 29, 37, 32, 38],
       [21, 19, 27, 35, 32, 10],
       [13, 33, 39, 37, 35, 37]])

In [39]:
c[2:2]

array([], shape=(0, 6), dtype=int32)

In [41]:
c[2:3]

array([[23, 15, 18, 27, 36, 29]])

In [43]:
c[0:-2]

array([[21, 12, 21, 13, 35, 31],
       [10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29],
       [17, 19, 29, 37, 32, 38]])

In [45]:
c

array([[21, 12, 21, 13, 35, 31],
       [10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29],
       [17, 19, 29, 37, 32, 38],
       [21, 19, 27, 35, 32, 10],
       [13, 33, 39, 37, 35, 37]])

In [51]:
c[1:-3]

array([[10, 37, 37, 26, 24, 18],
       [23, 15, 18, 27, 36, 29]])

In [53]:
c1 = np.random.randint(10,50,(7,7))
c1

array([[27, 41, 10, 32, 15, 43, 24],
       [19, 47, 48, 13, 43, 31, 17],
       [44, 32, 38, 24, 26, 29, 28],
       [38, 21, 48, 16, 33, 21, 41],
       [19, 33, 13, 15, 41, 20, 11],
       [19, 49, 43, 36, 11, 22, 13],
       [38, 35, 12, 37, 47, 15, 22]])

In [55]:
c1[1:-3]

array([[19, 47, 48, 13, 43, 31, 17],
       [44, 32, 38, 24, 26, 29, 28],
       [38, 21, 48, 16, 33, 21, 41]])

In [ ]:
Row 0 → [ 1,  2,  3,  4,  5,  6 ]  
Row 1 → [ 7,  8,  9, 10, 11, 12 ]  <-- Start from here (index 1)  
Row 2 → [13, 14, 15, 16, 17, 18 ]  
Row 3 → [19, 20, 21, 22, 23, 24 ]  <-- Stop before row -3 (row 3 tak lega)  
Row 4 → [25, 26, 27, 28, 29, 30 ]  (Excluded)  
Row 5 → [31, 32, 33, 34, 35, 36 ]  (Excluded)  

In [57]:
c1

array([[27, 41, 10, 32, 15, 43, 24],
       [19, 47, 48, 13, 43, 31, 17],
       [44, 32, 38, 24, 26, 29, 28],
       [38, 21, 48, 16, 33, 21, 41],
       [19, 33, 13, 15, 41, 20, 11],
       [19, 49, 43, 36, 11, 22, 13],
       [38, 35, 12, 37, 47, 15, 22]])

In [59]:
c1[-5,-3]

26

In [61]:
c1[-4,-2]

21

In [63]:
c1

array([[27, 41, 10, 32, 15, 43, 24],
       [19, 47, 48, 13, 43, 31, 17],
       [44, 32, 38, 24, 26, 29, 28],
       [38, 21, 48, 16, 33, 21, 41],
       [19, 33, 13, 15, 41, 20, 11],
       [19, 49, 43, 36, 11, 22, 13],
       [38, 35, 12, 37, 47, 15, 22]])

In [67]:
c1[-4:2]

array([], shape=(0, 7), dtype=int32)

### Operation

In [70]:
a = np.random.randint(10,20,10)
a

array([19, 19, 14, 16, 17, 19, 10, 10, 12, 11])

In [72]:
id(a)

2803878296528

In [74]:
arr 

NameError: name 'arr' is not defined

In [83]:
arr = np.random.randint(0,100,(10,10))
arr

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [85]:
arr[:]

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [87]:
arr[:4]

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14]])

In [89]:
arr[0:5]

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83]])

In [91]:
arr[1,4]

74

In [93]:
arr[::-1]      # reverse

array([[29, 27,  0, 42, 50, 44, 23, 81,  1, 27],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [70,  1,  3, 47, 57, 79, 72, 69,  6, 96]])

In [95]:
arr

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [97]:
arr[::-2]   # backword print step -2 Row

array([[29, 27,  0, 42, 50, 44, 23, 81,  1, 27],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71]])

In [99]:
arr

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [101]:
arr[::-3]

array([[29, 27,  0, 42, 50, 44, 23, 81,  1, 27],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [70,  1,  3, 47, 57, 79, 72, 69,  6, 96]])

In [103]:
arr[:-3]   # Removed last -3 row after that print all row

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8]])

In [105]:
arr[3:]  # start 3 row to end row

array([[43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [107]:
arr

array([[70,  1,  3, 47, 57, 79, 72, 69,  6, 96],
       [19, 55, 41, 13, 74, 24, 24, 91, 76, 71],
       [96, 74, 36, 64,  6, 51, 52, 72, 89,  5],
       [43, 58, 43, 26, 58, 41, 41,  7, 55, 14],
       [17, 63, 67,  0, 59, 38, 62, 87, 90, 83],
       [61, 77, 64, 15, 63, 82, 28, 45, 95,  0],
       [53, 91,  8, 47, 99, 41, 60, 78, 10,  8],
       [13, 96, 69, 21, 48, 14,  9, 90, 51, 95],
       [91, 31,  9, 99, 80, 89, 82, 15,  9, 72],
       [29, 27,  0, 42, 50, 44, 23, 81,  1, 27]])

In [109]:
arr1 = np.random.randint(10,20,(1,1))
arr1

array([[11]])

In [113]:
arr1 = np.random.randint(10,20,(1,10))
arr1

array([[12, 16, 10, 11, 14, 15, 10, 16, 11, 14]])

In [115]:
arr1.max()

16

In [117]:
arr1.min()

10

In [119]:
arr1.mean()

12.9

In [121]:
arr1

array([[12, 16, 10, 11, 14, 15, 10, 16, 11, 14]])

In [123]:
arr1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [129]:
from numpy import * 
a = array([1,2,3,4,9])
median(a)

3.0

In [131]:
arr1

array([[12, 16, 10, 11, 14, 15, 10, 16, 11, 14]])

In [138]:
arr1.reshape(5,2)

array([[12, 16],
       [10, 11],
       [14, 15],
       [10, 16],
       [11, 14]])

In [144]:
arr1.reshape(5,2,order='c')

array([[12, 16],
       [10, 11],
       [14, 15],
       [10, 16],
       [11, 14]])

In [ ]:
order='C': This means the data will be filled in row-major order (C-style). 
That is, rows will be filled first, then move to the next row.

In [161]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [165]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

reshaped_arr = arr3.reshape(5, 2, order='C')

print(reshaped_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [167]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
arr3.reshape(5,2,order='F')

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
If you use order='F', the data will be filled in column-major order (Fortran-style),
meaning columns will be filled first instead of rows.

In [171]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr3.reshape(5,2,order='A')

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
In NumPy, arr3.reshape(5,2, order='A') means reshaping the array arr3 into a shape of (5,2) while using the "A" 
(Any) order, which adapts based on the memory layout of the input array.

Meaning of order='A':

If arr3 is stored in C-order (row-major order), then order='A' behaves like order='C' (row-wise filling).

If arr3 is stored in Fortran-order (column-major order), then order='A' behaves like order='F' (column-wise filling).

If arr3 is neither strictly C nor F order, NumPy defaults to C-order

In [175]:
arr3.reshape(2,5,order='A')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [177]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
row=4
col=5
row

4

In [185]:
col

5

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[row,col]

45

In [191]:
mat[3,4]   # means 3rd row ka 4th colum ka value..it will print 3rd row and 4th col value

34

In [193]:
mat[6]  # it will print 7 rows, start with 0 index

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [199]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [203]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [ ]:
In NumPy, mat[:, col] means selecting a specific column (col) from the entire matrix (mat).

: (colon) is for rows → It means select all rows.
    
col (any integer value) is for columns → It means select only the specified column.
    
The output will be a 1D array (column vector) containing only the elements from that column.




In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
In NumPy, mat[row, :] means selecting a specific row (row) from the entire matrix (mat).

Breakdown:

row (any integer value) is for selecting a specific row.
    
: (colon) is for columns → It means select all columns from that row.

The output will be a 1D array (row vector) containing all the elements from that row.

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[2,:]   # Third row (0-based index)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [213]:
mat[4,:]   # 5th row (0-based index)

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[2:6,2:4]   ##This selects rows 2 to 5 and columns 2 to 3.

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
2:6 → Selects rows from index 2 to 5 (because slicing excludes the last index 6).

2:4 → Selects columns from index 2 to 3 (because slicing excludes the last index 4).

The result will be a smaller matrix (submatrix) containing elements from the specified row and column range.


In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[2:7,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64]])

In [223]:
mat[1:2,2:4]

array([[12, 13]])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat[2:3,2:3]

array([[22]])

In [229]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

### Masking

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
id(mat)

2803910897040

In [236]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [238]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [240]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [242]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [248]:
mat!=50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])